// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM3NMR9XJajPMdTgmSSGoZ5SdtZ00JHJ0',
    appId: '1:284112264945:android:58979fbf6f9047dc84d350',
    messagingSenderId: '284112264945',
    projectId: 'dalel-app-5a35f',
    storageBucket: 'dalel-app-5a35f.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb6HOR0xH7pMtL8vmU31-iLwNrvHvdZgw',
    appId: '1:284112264945:web:b66aea62eeb059d984d350',
    messagingSenderId: '284112264945',
    projectId: 'dalel-app-5a35f',
    authDomain: 'dalel-app-5a35f.firebaseapp.com',
    storageBucket: 'dalel-app-5a35f.firebasestorage.app',
    measurementId: 'G-Z7ZZBGRGQ4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLeslQii8i8EiAxfTVks9X3-vxfRKiJGo',
    appId: '1:284112264945:ios:0957ab8918f2d71f84d350',
    messagingSenderId: '284112264945',
    projectId: 'dalel-app-5a35f',
    storageBucket: 'dalel-app-5a35f.firebasestorage.app',
    iosBundleId: 'com.example.dalelApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLeslQii8i8EiAxfTVks9X3-vxfRKiJGo',
    appId: '1:284112264945:ios:0957ab8918f2d71f84d350',
    messagingSenderId: '284112264945',
    projectId: 'dalel-app-5a35f',
    storageBucket: 'dalel-app-5a35f.firebasestorage.app',
    iosBundleId: 'com.example.dalelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb6HOR0xH7pMtL8vmU31-iLwNrvHvdZgw',
    appId: '1:284112264945:web:33975472687e618084d350',
    messagingSenderId: '284112264945',
    projectId: 'dalel-app-5a35f',
    authDomain: 'dalel-app-5a35f.firebaseapp.com',
    storageBucket: 'dalel-app-5a35f.firebasestorage.app',
    measurementId: 'G-9FRK1T2YGE',
  );

}